version: '3.8'
services:
  web:
    build:
      context: ./docker/web/dev
    depends_on:
      - db
      - db_test
    env_file:
      - .env.local
    volumes:
      - ./symfony:/var/www/html/
      - ~/.composer:/var/composer:cached
      - ./docker/web/vhost.conf:/etc/apache2/sites-enabled/vhost.conf
      - ./docker/web/dev/php.ini:/usr/local/etc/php/php.ini
      - ./docker/web/dev/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    ports:
      - "80:80"
  db:
    image: mariadb:10.4.32
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/db/init:/docker-entrypoint-initdb.d
    env_file:
      - .env.local
    ports:
      - "3306:3306"
  db_test:
    image: mariadb:10.3.31
    volumes:
      - db_data_test:/var/lib/mysql
      - ./docker/db_test/init:/docker-entrypoint-initdb.d
    env_file:
      - .env.test
    ports:
      - "3307:3306"
  mail:
    image: 'dockage/mailcatcher:0.8.2'
    ports:
      - "1081:1080"
  redis:
    image: redis:5-alpine
    ports:
      - "6379:6379"
  node:
    image: node:16
    volumes:
      - './symfony:/usr/app'
    restart: on-failure
    entrypoint: "tail -f /dev/null"
    working_dir: "/usr/app"
    ports:
      - "8083:8083"
volumes:
  db_data: {}
  db_data_test: {}
